


// a
var story = [{ id: "", link: "", sentence: "There is only one way to understand the 1,933-mile line that divides our country from Mexico."
}, { id: "", link: "", sentence: "Start at the beach and walk east until you hit the Gulf."
}, { id: "", link: "", sentence: "The fence starts about eighty feet out into the Pacific and is made of metal pylons."
}, { id: "", link: "", sentence: "Once it hits dry land, it goes up the beach and onto a little hill."
}, { id: "", link: "", sentence: "There it becomes two fences and looks more like a prison barrier."
}, { id: "", link: "", sentence: "One fence follows the border line and the other runs parallel, north of it."
}, { id: "", link: "", sentence: "The buffer zone between the two is reserved for the US Border control, except for when, on Saturdays and Sundays citizens are allowed to enter to look at and talk to Mexicans on the other side."
}, { id: "", link: "", sentence: "However, they are not allowed physical contact with them."

// b"
}, { id: "", link: "", sentence: "This place is called the “Friendship Circle” and a marble obelisk stands in its center, breaking the fence."
}, { id: "", link: "", sentence: "In 1851, some men from something called the International Boundary Commission placed the obelisk here."
}, { id: "", link: "", sentence: "The International Boundary Commission started on the beachfront hill when revising the border between the two countries and the obelisk was their first survey marker."
}, { id: "", link: "", sentence: "Back then, the Mexican-American War had just ended, and Mexico had agreed to surrender more than half its territory to the United States, including the places now called California, Arizona, New Mexico, and Texas."
}, { id: "", link: "", sentence: "The job of the International Boundary Commission was to come up with a map of the revised frontier between the two countries."
}, { id: "", link: "", sentence: "They started here, on this beachfront hill, and installed the obelisk as their first survey marker."
}, { id: "", link: "", sentence: "Then they walked east, into the borderlands, on a dangerous journey."
}, { id: "", link: "", sentence: "They had only two choices of transportation – by foot or by horse."
}, { id: "", link: "", sentence: "Today you can fly or drive in just a short amount of time."
}, { id: "", link: "", sentence: "But if you really want to understand something, sometimes you have to slow down."

// c"
}, { id: "", link: "", sentence: "So this morning, like the men who planted the obelisk, I start on the beach and walk east."
}, { id: "", link: "", sentence: "The border is simple, heading east across California, then backtracking a bit at the Colorado river where it squiggles southwest along the river’s edge and then slices straight across Arizona."
}, { id: "", link: "", sentence: "When it reaches New Mexico is heads north for a few dozen miles and then resumes eastward to Texas, where it merges with the Rio Grande in the final stretch to the Gulf."
}, { id: "", link: "", sentence: "The border is complicated, as from a distance it looks complex and chaotic."
}, { id: "", link: "", sentence: "Although it is tempting, we shouldn’t look away from it because it is where we end and they begin."

// d"
}, { id: "", link: "", sentence: "There are certain problems in walking along the border, since the only way to walk along the borderline is to follow the Border Patrol’s dirt roads, but the Border Patrol does not give out maps of these roads to the public."
}, { id: "", link: "", sentence: "You can use satellite imagery, but these are not always current because new roads are being plowed."
}, { id: "", link: "", sentence: "Additionally, any route you select is a mix of deserts and mountains."
}, { id: "", link: "", sentence: "An example of these problems is an area called Smuggler’s Gulch, east of Friendship Circle, where maps show a deep ravine used by drug and human traffickers for decades."
}, { id: "", link: "", sentence: "But a few years ago, the Department of Homeland Security sent in earthmovers to flatten the area and top it with a Border Patrol road and floodlights."
}, { id: "", link: "", sentence: "My maps are wrong."

// e"
}, { id: "", link: "", sentence: "My plan is to stick to the border roads where I can find them, but where there isn’t one, I’ll let myself drift north."
}, { id: "", link: "", sentence: "My first chunk is 350 miles long, to Ajo, Arizona, including 120 miles of open desert called El Camino del Diablo."
}, { id: "", link: "", sentence: "The problem there is lack of water, as it a dry area and I cannot carry enough water on my back."
}, { id: "", link: "", sentence: "If this were a century and a half ago, I would have brought a mule."
}, { id: "", link: "", sentence: "Instead, I have got a baby stroller."

// f
}, { id: "", link: "", sentence: "\"You need help?\" Feet digging, ankles stretched, calves tight, knees bent, back straight, shoulders up, head down, arms out, palms open, leaning forward, into the handlebar."
}, { id: "", link: "", sentence: "The handlebar doubles as a rack to hang things on, such as a Garmin GPS, a thirty-two-ounce Nalgene water bottle, a Spot emergency locator beacon, and a can of Counter Assault Bear Deterrent pepper spray."

// g"
}, { id: "", link: "", sentence: "I look up, but I don\'t stop leaning."
}, { id: "", link: "", sentence: "The stroller and everything in it weighs more than 120 pounds."
}, { id: "", link: "", sentence: "I am near the top of the Otay Mountain and the incline is steep, at least 45 degrees, so if I stop leaning the stroller will roll back and down the slope."
}, { id: "", link: "", sentence: "The agent is standing on the top of the rise, looking down and holding a pair of binoculars."

// h"
}, { id: "", link: "", sentence: "\"I saw you coming from a ways away,\" he says."
}, { id: "", link: "", sentence: "The border is about nineteen hundred miles long, with about eighteen thousand Border Patrol agents protecting it."
}, { id: "", link: "", sentence: "That\'s nine agents per mile."
}, { id: "", link: "", sentence: "But these agents aren\'t posted at regular intervals, sometimes moving around, clustering, pursuing leads or manning checkpoints."
}, { id: "", link: "", sentence: "If you\'re walking the border, you\'re going to see a lot of Border Patrol."
}, { id: "", link: "", sentence: "I push the final few feet to the top of the rise and lock the stroller\'s wheels and stop to chat with the agent."
}, { id: "", link: "", sentence: "The eastern flank of Otay Mountain drops two thousand feet into a deep valley that runs north to Highway 94 and south to Mexico."
}, { id: "", link: "", sentence: "I can see the fence and some cars passing by behind it."
}, { id: "", link: "", sentence: "That\'s where they cross, the agent tells me."
}, { id: "", link: "", sentence: "It\'s best to spot them as soon as they hop the fence, because once they enter the thick foliage of the valley, they become a lot harder to see."
}, { id: "", link: "", sentence: "I give him back his binoculars and keep walking."
}, { id: "", link: "", sentence: "This spot on the Otal Mountain has a great view of the ocean and the flora that descends to it."
}, { id: "", link: "", sentence: "It’s beautiful."

// i"
}, { id: "", link: "", sentence: "I hope to average twenty miles a day, but the mountain is steep and the cart is heavy and I only make it ten today before dark."
}, { id: "", link: "", sentence: "I stop and make camp on a clearing beside the trail, and fall asleep immediately though I wake up every time patrols pass my tent."
}, { id: "", link: "", sentence: "At dawn I get up, get ready, and start again."
}, { id: "", link: "", sentence: "Coming down the mountain is easier than climbing it so I relax a bit."

// j"
}, { id: "", link: "", sentence: "Every few miles, I\'ll run into an agent, who\'ll ask what I\'m doing out here."
}, { id: "", link: "", sentence: "Sometimes he\'ll ask to see the soles of my shoes, since agents spend a lot of time looking for fresh footprints in the dirt that may belong to aliens."
}, { id: "", link: "", sentence: "If they see the shoes of a non-alien, they can ignore that print later on."
}, { id: "", link: "", sentence: "Sometimes I\'ll see agents when they\'re not really there."
}, { id: "", link: "", sentence: "I\'ll spot their parked vehicles, but only when I come close and look through their windows do I see that about a third are empty."
}, { id: "", link: "", sentence: "The trail from Otay Mountain feeds into State Route 94, and I follow the highway east for about ten miles, then cut south toward the border again."

// k"
}, { id: "", link: "", sentence: "I spot a truck with an agent inside and tap on the window."
}, { id: "", link: "", sentence: "He rolls it down and gives me a nod."
}, { id: "", link: "", sentence: "People call this town Tecatito because it sits across the border from the much bigger town of Tecate, Mexico."
}, { id: "", link: "", sentence: "The agent\'s truck is pointed straight south, where someone occasionally walks out of the Customs building and into America."
}, { id: "", link: "", sentence: "He can see a poster on the wall with head shots of Hispanic man and details of what they are wanted for."
}, { id: "", link: "", sentence: "I tell him I\'m going across and that I\'ll have to walk through most of Tecate to get to my hotel."
}, { id: "", link: "", sentence: "Does he think I\'ll have any problems, safety wise? Tecate\'s not too bad these days, he says."
}, { id: "", link: "", sentence: "From what he hears, anyway."
}, { id: "", link: "", sentence: "He\'s never crossed himself."

// l"
}, { id: "", link: "", sentence: "The passport-control booth is empty so I just walk across the line."
}, { id: "", link: "", sentence: "I love Mexico."
}, { id: "", link: "", sentence: "I lived there briefly as a kid and used to visit all the time."
}, { id: "", link: "", sentence: "I love the language, the food, the pace, the people, the temperature."
}, { id: "", link: "", sentence: "However, Mexico scares me."
}, { id: "", link: "", sentence: "The last time I visited, I was driving around a small city with an off-duty police detective, in his car."
}, { id: "", link: "", sentence: "He wasn’t in uniform and at first, he was relaxed, telling stories about his adventures until he realized, at a stoplight, that his wallet with the badge in it was lying open on the dash."
}, { id: "", link: "", sentence: "A jolt went through his body and he scrambled to hide it and check if anyone in the other vehicles had noticed it."
}, { id: "", link: "", sentence: "That kind of fear is contagious and I hate how it’s a part of my experience and a part of the background texture of Tecate."
}, { id: "", link: "", sentence: "Because without the the fear, all the best parts of Mexico are still here."

// m"
}, { id: "", link: "", sentence: "Tonight I eat a restaurant near my hotel."
}, { id: "", link: "", sentence: "I drink a few bottles of local brew and have a shot, and it’s the best meal I’ve had in months."

// n"
}, { id: "", link: "", sentence: "\"You weren\'t wearing those earlier.\" He\'s got his flashlight aimed at my flip-flops and I tell him they\'re my camp shoes."
}, { id: "", link: "", sentence: "Agent Muñoz shines the light through the trees, toward the tent."

// o"
}, { id: "", link: "", sentence: "\"Anyone else back there?\" No."
}, { id: "", link: "", sentence: "We\'re a few hundred feet north of the border, on a low rise beside a dry creek bed."
}, { id: "", link: "", sentence: "I walked a long and difficult terrain today and the desert was beginning to show."
}, { id: "", link: "", sentence: "I\'d already made camp and was finishing my dinner when Agent Muñoz rolled up."

// p"
}, { id: "", link: "", sentence: "\"Strange place to camp,\" he says."
}, { id: "", link: "", sentence: "I tell him I chose it because it\'s not right next to the fence, and I am not visible from it."
}, { id: "", link: "", sentence: "I had been told not to camp next to the fence because I am vulnerable at night to bandits who can take whatever they want without getting caught."
}, { id: "", link: "", sentence: "Agent Muñoz listens, nods."

// q"
}, { id: "", link: "", sentence: "\"You\'ve never been here before?\"."
}, { id: "", link: "", sentence: "No, I haven\'t."
}, { id: "", link: "", sentence: "He shifts his hips, relaxes a bit."
}, { id: "", link: "", sentence: "\"I wouldn\'t camp here,\" he says."
}, { id: "", link: "", sentence: "\"I don\'t even like to be here.\" He explains that my spot is actually a bad place because it is shielded by trees and drug mules often come through it."
}, { id: "", link: "", sentence: "\"We\'ve got some pressure sensors buried farther up the creek,\" he says."
}, { id: "", link: "", sentence: "\"We send out a team anytime they get a hit."
}, { id: "", link: "", sentence: "But that takes a while.\" Should I pack up my tent? Would I be safer somewhere else? He shakes his head."
}, { id: "", link: "", sentence: "\"Nowhere\'s safe around here.\""

// r"
}, { id: "", link: "", sentence: "He gives me the direct line to the nearest station, tells me to call if I see anyone, and drives away."
}, { id: "", link: "", sentence: "\"Tell them you\'re in the bottom of La Gloria."
}, { id: "", link: "", sentence: "Everyone knows where that is.\" Soon it is dark again and I think of everything I can use as a weapon."
}, { id: "", link: "", sentence: "I bring it all inside the tent and lie in the bag, listening to the sounds outside."
}, { id: "", link: "", sentence: "But every time I turn on my headlamp I see nothing and it feels like a world of unknowns is outside pressing in."
}, { id: "", link: "", sentence: "Another gust spits sand into my face so I give in and lean against the fence, my back to the wind."
}, { id: "", link: "", sentence: "The fence here, a few miles past La Gloria, is crude but strong, made of steel."
}, { id: "", link: "", sentence: "The National Guard built it in 2006, and every engineering battalion left its mark on the section it built."
}, { id: "", link: "", sentence: "The builders came from all around the country and worked even through the holidays, judging by the spray-painted Christmas tree I lean next to."
}, { id: "", link: "", sentence: "The fence is tall and would be tough to climb over or tear through, but I see a spot where the dirt next to the fence has been dug into a hole I could climb through."
}, { id: "", link: "", sentence: "There\'s a yellow sign on the other side of the road with a drawing of a drowning man."
}, { id: "", link: "", sentence: "CUIDADO! the sign reads."
}, { id: "", link: "", sentence: "NO VALE LA PENA!"

// s"
}, { id: "", link: "", sentence: "It\'s not worth the trouble! But of course it is."
}, { id: "", link: "", sentence: "By crossing the line, a man boosts his earning potential sixfold and if he chooses to carry something with him, a pound of cocaine costs twice as much in Tecatito than it does in Tecate."
}, { id: "", link: "", sentence: "It\'s worth the trouble, and so every year roughly 2.5 million people make the decision to cross illegally."

// t"
}, { id: "", link: "", sentence: "Consequently, the fence and Border Patrol, have more than doubled in the last decade, though the incursions haven\'t stopped."
}, { id: "", link: "", sentence: "Instead, they\'ve shifted."
}, { id: "", link: "", sentence: "Near San Diego, traffic has slowed but here, where the fence less sturdy and there are less patrol, it has increased."
}, { id: "", link: "", sentence: "As long as there is any gap or weakness in the border, they will find a way."
}, { id: "", link: "", sentence: "Because of this, I wonder why I still haven\'t run into any crossers myself."
}, { id: "", link: "", sentence: "The wind easies and I start walking again."
}, { id: "", link: "", sentence: "I hear and see things occasionally, murmurs and blurs of fabric, but when I stop to look and listen, everything goes still."
}, { id: "", link: "", sentence: "Eventually I come to a spot where the fence continues east while the road goes north."
}, { id: "", link: "", sentence: "I follow the road to an abandoned track and then reach Old Highway 80 which takes me south to a long concrete bridge."
}, { id: "", link: "", sentence: "At the end of it, a sign says, wELCOME TO JACUMBA."
}, { id: "", link: "", sentence: "A smaller one below it, with a little drawing of a woman dressed in a 1910-style bathing suit, reads JACUMBA HOT SPRINGS ..."
}, { id: "", link: "", sentence: "ALL YOUR WANTS."

// u"
}, { id: "", link: "", sentence: "The manager\'s smoking a cigarette outside and he gives me the key to a room."
}, { id: "", link: "", sentence: "I shower and change, and come back outside to see the manager still standing there, smoking."
}, { id: "", link: "", sentence: "Except for the convenience store across the street from the hotel and Laundromat next to it, almost everything here has gone out of business."
}, { id: "", link: "", sentence: "A group of Border Patrol agents are milling around, waiting for something."
}, { id: "", link: "", sentence: "I ask the manager about Jacume, the town directly across the fence from Jacumba."
}, { id: "", link: "", sentence: "I\'d read about Jacume, called a “black hole” by the Los Angeles Times, overrun by smugglers."
}, { id: "", link: "", sentence: "Even the Mexican cops won\'t go near it."
}, { id: "", link: "", sentence: "The manager tells me that Jacumba and Jacume used to be close and before the fence went up, people from Jacume used to cross to work and shop in Jacumba, and people from Jacumba used to cross to eat and party in Jacume."
}, { id: "", link: "", sentence: "Now they are just towns on the border."

// v"
}, { id: "", link: "", sentence: "\"I hear Jacume\'s real dangerous now,\" he says."
}, { id: "", link: "", sentence: "\"But I don\'t really have any idea what goes on down there.\""

// w"
}, { id: "", link: "", sentence: "A few minutes later, the agents take off running toward the fence, as if a silent alarm went off."
}, { id: "", link: "", sentence: "After Jacumba, the fence road fades out again, and I have to stick to the asphalt."
}, { id: "", link: "", sentence: "I stay on it for a week, averaging twenty-five miles per day."
}, { id: "", link: "", sentence: "Highways were never meant for walking on and their unrelenting sameness turns the whole week into a set of disconnected impressions."
}, { id: "", link: "", sentence: "The cherry-red semi that passes too close and fast, almost hitting me."
}, { id: "", link: "", sentence: "The little leather pouch lying on the shoulder with COLUMBIA stenciled on it and mix of pesos and pennies inside."
}, { id: "", link: "", sentence: "The flat camp is see in the Yuha Desert and how long it takes me to find a clear spot for my tent."
}, { id: "", link: "", sentence: "I take off days in a hotel along the way and tend to my blistered feet."
}, { id: "", link: "", sentence: "A middle-aged man in the hotel bar shows me the crowns on his teeth he bought to cheap across the border in Algodones."
}, { id: "", link: "", sentence: "The bartender tells me a story about cartels cloning vehicles and uniforms of a contracting company in order to drive their stuff freely across the border while the fence was being built."

// x"
}, { id: "", link: "", sentence: "The Imperial Dunes, buzzing all day and night with tricked-out hot-rod sand buggies."

// y"
}, { id: "", link: "", sentence: "The retired Border Patrol agent in Yuma who says he loved his job, then quotes Hemingway: \"There is no hunting like the hunting of man.\""

// z"
}, { id: "", link: "", sentence: "My blisters get so bad on my heels that I start jogging instead of walking, just to change the point of impact."
}, { id: "", link: "", sentence: "Finally, I can see the beginning of the Camino del Diablo."

// aa"
}, { id: "", link: "", sentence: "In August of 1905, a prospector named Pablo Valencia went south, into the desert from Wellton in search of a lost gold mine."
}, { id: "", link: "", sentence: "He was about forty years old, 155 pounds, rode a good horse, and brought six gallons of water and plenty of food."
}, { id: "", link: "", sentence: "On the first day he rode thirty four miles and reached a spot by the Gila Mountains where the Camino del Diablo began."
}, { id: "", link: "", sentence: "West of the spot was Tinajas Altas, where eroded stone basins contained rainwater, the only semi reliable water source in the area."
}, { id: "", link: "", sentence: "Valencia refilled his canteens there and ran into geologist WJ McGee who had set up camp nearby."
}, { id: "", link: "", sentence: "The two men shared a meal together before Valencia departed eastward."
}, { id: "", link: "", sentence: "Eight days later, at dawn, McGee heard an inhuman shriek and followed it to its source."
}, { id: "", link: "", sentence: "He discovered Valencia, previously in great condition, naked, emaciated, blackened, and completely shriveled to the point of deformation."
}, { id: "", link: "", sentence: "He was one of few to survive the Camino del Diablo and to eventually recover from the state of extreme dehydration."

// bb"
}, { id: "", link: "", sentence: "I walk south from Wellton for a day and a half before I reach Tinajas Altas, leave my stroller on the trail, and scramble up the rocks to the lowest tank."
}, { id: "", link: "", sentence: "It\'s half full of greenish rainwater."
}, { id: "", link: "", sentence: "A quarter mile away lies the \"mesita de los muertos,\" a little mesa topped with anonymous with crosses under which lie the bones of about sixty people, who died in the area, unable to reach water."
}, { id: "", link: "", sentence: "I head east, onto the Camino del Diablo, with eight gallons in my stroller."
}, { id: "", link: "", sentence: "A big chunk of the Camino runs though the U."
}, { id: "", link: "", sentence: "S."
}, { id: "", link: "", sentence: "Air Force\'s Barry M."
}, { id: "", link: "", sentence: "Goldwater Range and to gain entry, I signed a liability release that read that I accepted the \"danger of property damage and permanent, painful, disabling, and disfiguring injury or death due to high explosive detonations from falling objects such as aircraft, aerial targets, live ammunition, missiles, bombs, etc.\" Soon after leaving the Tinajas Altas, I hear a roaring sound and see two F-16 fighter jets that head towards me along the desert floor before shooting up into the sky."

// cc"
}, { id: "", link: "", sentence: "It\'s early afternoon, my third day on the Camino, and the sand on this part of the trail is too deep for my stroller, so I\'m up on the thin crust of the desert instead, stumbling through the rough terrain."
}, { id: "", link: "", sentence: "I see a Border Patrol truck coming, kicking up dust, as I stop and watch it approach."
}, { id: "", link: "", sentence: "Two agents."
}, { id: "", link: "", sentence: "Both Hispanic, early thirties."
}, { id: "", link: "", sentence: "Neither is wearing a uniform."
}, { id: "", link: "", sentence: "The passenger gives a curt nod in my direction, but the driver offers a big smile, asks what I\'m doing out here, and where I\'m going."
}, { id: "", link: "", sentence: "I tell him."

// dd"
}, { id: "", link: "", sentence: "\"Ajo!\" he says."
}, { id: "", link: "", sentence: "\"That\'s a long way away.\""

// ee"
}, { id: "", link: "", sentence: "They drive off and I fall back into my stupor, walking, until about a half hour later when I notice that the same Border Patrol vehicle is stopped at a bend in the trail in the distance, just parked there, idling."
}, { id: "", link: "", sentence: "Your head does funny things."
}, { id: "", link: "", sentence: "You\'re all alone for hours at a stretch, and your solitude does not lend itself to deep contemplation."
}, { id: "", link: "", sentence: "Mostly you just fall into half-trances, with no thoughts at all, until some unexpected stimulus intrudes and seizes hold of your mind."
}, { id: "", link: "", sentence: "I start thinking about the guys in the truck."
}, { id: "", link: "", sentence: "Why weren\'t they wearing uniforms? And why was the passenger so curt, so unfriendly? And why, for that matter, was the driver so friendly? Then I start thinking about the cartels and how good they are at cloning vehicles."
}, { id: "", link: "", sentence: "I move a little ways farther off the trail, though it seems pretty futile."
}, { id: "", link: "", sentence: "There really is nowhere to run and there may not by another human being for forty miles in any direction."
}, { id: "", link: "", sentence: "When I\'m even with the truck, but about a hundred feet off the trail, I look over and the driver is still sitting in the driver\'s seat, and he smiles and waves."
}, { id: "", link: "", sentence: "Then I notice the passenger, lying next to the truck, partly beneath it, trying to fix something on the undercarriage."

// ff"
}, { id: "", link: "", sentence: "More hours, more miles."
}, { id: "", link: "", sentence: "When the sun starts going down, I see orange-black rocks, the Pinacate lava field."
}, { id: "", link: "", sentence: "It\'s below freezing, a lot colder than it\'s supposed to be in Arizona."
}, { id: "", link: "", sentence: "By the time I\'ve got the tent set up, my blood has slowed and the air is numbing my fingers."
}, { id: "", link: "", sentence: "I eat quickly and then get into my bag wearing still dressed, trying to keep warm."
}, { id: "", link: "", sentence: "I sleep for a while, until the wind wakes me."

// gg"
}, { id: "", link: "", sentence: "It has lifted up a whole side of the tent, ripping out all the stakes, and is blowing so hard that the floor has doubled over, coming down on top of me."
}, { id: "", link: "", sentence: "I unzip my bag enough to get my hands out and push the floor up off of me and the wind whips the polyester around my hands."
}, { id: "", link: "", sentence: "Eventually it dies down and the floor settles and I zip all the way up again and try to sleep, but then I realize I need to piss."
}, { id: "", link: "", sentence: "It\'s 1:00 A.M."
}, { id: "", link: "", sentence: "and the orange-black rocks just look gray now."
}, { id: "", link: "", sentence: "The water bottle I left outside is iced up."
}, { id: "", link: "", sentence: "The wind starts up again while I\'m pissing, and I hold on to the tent with my other hand to keep it still."
}, { id: "", link: "", sentence: "There\'s a red light throbbing in the distance, above the top of a mountain."
}, { id: "", link: "", sentence: "At first I think maybe it\'s a radio but it looks like it\'s floating, like a throbbing red orb."
}, { id: "", link: "", sentence: "Another night I saw a different light, on the ground, like a flashlight beam and it has scared me."
}, { id: "", link: "", sentence: "I had grabbed my satellite communicator and held the SOS button, watching the beam until it disappeared behind some rocks."
}, { id: "", link: "", sentence: "But this light was not scary, just intriguing."
}, { id: "", link: "", sentence: "I go crawl into the tent to get my camera but am too cold to crawl back out."
}, { id: "", link: "", sentence: "At dawn the light is gone."

// hh"
}, { id: "", link: "", sentence: "The Camino del Diablo is older than America, extending from Tinajas Altas for a hundred miles."
}, { id: "", link: "", sentence: "Nobody knows who created the trail, but a thousand years ago it was already ancient."
}, { id: "", link: "", sentence: "Young Papago Indians would make holy pilgrimages on it, a regiment of conquistadores may have ridden here in the 1500s, but the first Europeans here were the Jesuit missionaries in 1699."
}, { id: "", link: "", sentence: "It earned its name during the Gold Rush when hundreds of miners and their families dried up and died here, trying to reach California."
}, { id: "", link: "", sentence: "The Camino mostly runs parallel and close to the border."
}, { id: "", link: "", sentence: "As border security has increased to the west, the Camino area has become a popular route for migrants and smugglers."
}, { id: "", link: "", sentence: "On a Saturday in May 2001, for example, fourteen men were dropped off near here, planning to walk north to reach the American highway."
}, { id: "", link: "", sentence: "They failed to cross the Growler Mountains and walked north along the range, before turning almost 180 degrees and walking southwest to the southern tip of the Granite range, and then turning again and heading northwest."
}, { id: "", link: "", sentence: "They wandered for 5 days, with too much sun and not enough water."
}, { id: "", link: "", sentence: "When the Border Patrol found them, there was nothing to do but collect their remains and belongings and turn them over to the Mexican Consulate."
}, { id: "", link: "", sentence: "They were known as the Yuma Fourteen, after the closest big city that they never made it to."

// ii"
}, { id: "", link: "", sentence: "More than a hundred people had already dried to death that year in this same desert, but because of the pressure to do something about it, Camp Grip was built to control this stretch of the border."

// jj"
}, { id: "", link: "", sentence: "I see Camp Grip and when I get close, I can smell hamburgers cooking and it smells good."
}, { id: "", link: "", sentence: "I ring the doorbell twice and knock, too."
}, { id: "", link: "", sentence: "An agent eventually comes to the door, surprised to see me."
}, { id: "", link: "", sentence: "We chat a bit."
}, { id: "", link: "", sentence: "Camp Grip has been a success, traffic has slowed, he says."
}, { id: "", link: "", sentence: "But there\'s still plenty of traffic."
}, { id: "", link: "", sentence: "I tell him about the red light I saw last night above the lava field."
}, { id: "", link: "", sentence: "He shrugs."

// kk"
}, { id: "", link: "", sentence: "\"There was a big group crossed last night near where you camped,\" he says."
}, { id: "", link: "", sentence: "\"We caught them earlier today, about twenty miles north."
}, { id: "", link: "", sentence: "They could have had someone up in the mountains, scouting for them."
}, { id: "", link: "", sentence: "That light might have been their go-ahead signal."
}, { id: "", link: "", sentence: "They\'ve got scouts all over the place."
}, { id: "", link: "", sentence: "Camouflage."
}, { id: "", link: "", sentence: "Radios."
}, { id: "", link: "", sentence: "Binoculars."
}, { id: "", link: "", sentence: "They\'re organized."
}, { id: "", link: "", sentence: "They\'re probably watching us right now.\""

// ll"
}, { id: "", link: "", sentence: "I wait until the morning air warms a little and then I sit up and unzip my bag and look at my feet."
}, { id: "", link: "", sentence: "Every morning, this is the first thing I do, since the night cold keeps them numb and I can’t tell if they’ve gotten worse or not."
}, { id: "", link: "", sentence: "I tend to my massive blisters, and bandage them."
}, { id: "", link: "", sentence: "Every day starts like this, and once I\'m done and put on my shoes, I try not to think about my feet at all until the next morning."
}, { id: "", link: "", sentence: "I get on the northward and start walking the final sixteen miles to Ajo."

// mm"
}, { id: "", link: "", sentence: "The New Cornelia Mine is an open pit a mile wide with rainwater at the bottom."
}, { id: "", link: "", sentence: "For seventy years the people of Ajo lived off the mine, until copper prices crashed and in 1984 the mine shut down."

// nn"
}, { id: "", link: "", sentence: "I follow the road to the dam\'s leading edge, then around the dam to the northeast, until I reach the intersection with State Route 85 and walk north."
}, { id: "", link: "", sentence: "I\'m looking forward to stopping for a while, to seeing my daughter, to letting my feet heal."
}, { id: "", link: "", sentence: "I walk faster and soon reach the outskirts of Ajo, passing by faux-Spanish-colonial buildings that look a lot older than they are."
}, { id: "", link: "", sentence: "When the International Boundary Commission passed through this area 50 years ago, Ajo didn\'t even exist."
}, { id: "", link: "", sentence: "I reach the Ajo Border Patrol Station."
}, { id: "", link: "", sentence: "The station looks a little run-down, a little overstuffed, too many cars crowded around too few buildings."
}, { id: "", link: "", sentence: "They\'ve started construction on a new station, right next to the old one, clearing and grading the land, getting it ready."
}, { id: "", link: "", sentence: "The existing station was designed for 25 agents."
}, { id: "", link: "", sentence: "The new one will accommodate 360, with room for future expansion."
}, { id: "", link: "", sentence: "It is to become Ajo\'s economic center and soon one in four people living in Ajo will either be a Border Patrol agent, the spouse of one, or the child of one."

// oo"
}, { id: "", link: "", sentence: "Twenty-seven miles farther south, the highway ends at the Lukeville crossing, and another new procession of steel and wire, built in 2008, marches east across the desert."

// pp"
}, { id: "", link: "", sentence: "That\'s where I\'ll begin again, when I return." }]